query FetchSeatGroups {
	seatGroups {
		edges {
			node {
				id
				name
				createdAt
				user {
					id
					email
				}
				seatGroupAccessRight {
					id
					level
					accessRight {
						id
						label
					}
				}
			}
		}
	}
}
