// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"delivrio.io/go/ent/carrier"
	"delivrio.io/go/ent/carrierbring"
	"delivrio.io/go/ent/predicate"
	"delivrio.io/go/ent/tenant"
	"delivrio.io/shared-utils/pulid"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CarrierBringQuery is the builder for querying CarrierBring entities.
type CarrierBringQuery struct {
	config
	ctx         *QueryContext
	order       []carrierbring.OrderOption
	inters      []Interceptor
	predicates  []predicate.CarrierBring
	withTenant  *TenantQuery
	withCarrier *CarrierQuery
	withFKs     bool
	modifiers   []func(*sql.Selector)
	loadTotal   []func(context.Context, []*CarrierBring) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CarrierBringQuery builder.
func (cbq *CarrierBringQuery) Where(ps ...predicate.CarrierBring) *CarrierBringQuery {
	cbq.predicates = append(cbq.predicates, ps...)
	return cbq
}

// Limit the number of records to be returned by this query.
func (cbq *CarrierBringQuery) Limit(limit int) *CarrierBringQuery {
	cbq.ctx.Limit = &limit
	return cbq
}

// Offset to start from.
func (cbq *CarrierBringQuery) Offset(offset int) *CarrierBringQuery {
	cbq.ctx.Offset = &offset
	return cbq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cbq *CarrierBringQuery) Unique(unique bool) *CarrierBringQuery {
	cbq.ctx.Unique = &unique
	return cbq
}

// Order specifies how the records should be ordered.
func (cbq *CarrierBringQuery) Order(o ...carrierbring.OrderOption) *CarrierBringQuery {
	cbq.order = append(cbq.order, o...)
	return cbq
}

// QueryTenant chains the current query on the "tenant" edge.
func (cbq *CarrierBringQuery) QueryTenant() *TenantQuery {
	query := (&TenantClient{config: cbq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cbq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cbq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(carrierbring.Table, carrierbring.FieldID, selector),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, carrierbring.TenantTable, carrierbring.TenantColumn),
		)
		fromU = sqlgraph.SetNeighbors(cbq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCarrier chains the current query on the "carrier" edge.
func (cbq *CarrierBringQuery) QueryCarrier() *CarrierQuery {
	query := (&CarrierClient{config: cbq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cbq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cbq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(carrierbring.Table, carrierbring.FieldID, selector),
			sqlgraph.To(carrier.Table, carrier.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, carrierbring.CarrierTable, carrierbring.CarrierColumn),
		)
		fromU = sqlgraph.SetNeighbors(cbq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CarrierBring entity from the query.
// Returns a *NotFoundError when no CarrierBring was found.
func (cbq *CarrierBringQuery) First(ctx context.Context) (*CarrierBring, error) {
	nodes, err := cbq.Limit(1).All(setContextOp(ctx, cbq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{carrierbring.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cbq *CarrierBringQuery) FirstX(ctx context.Context) *CarrierBring {
	node, err := cbq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CarrierBring ID from the query.
// Returns a *NotFoundError when no CarrierBring ID was found.
func (cbq *CarrierBringQuery) FirstID(ctx context.Context) (id pulid.ID, err error) {
	var ids []pulid.ID
	if ids, err = cbq.Limit(1).IDs(setContextOp(ctx, cbq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{carrierbring.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cbq *CarrierBringQuery) FirstIDX(ctx context.Context) pulid.ID {
	id, err := cbq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CarrierBring entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CarrierBring entity is found.
// Returns a *NotFoundError when no CarrierBring entities are found.
func (cbq *CarrierBringQuery) Only(ctx context.Context) (*CarrierBring, error) {
	nodes, err := cbq.Limit(2).All(setContextOp(ctx, cbq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{carrierbring.Label}
	default:
		return nil, &NotSingularError{carrierbring.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cbq *CarrierBringQuery) OnlyX(ctx context.Context) *CarrierBring {
	node, err := cbq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CarrierBring ID in the query.
// Returns a *NotSingularError when more than one CarrierBring ID is found.
// Returns a *NotFoundError when no entities are found.
func (cbq *CarrierBringQuery) OnlyID(ctx context.Context) (id pulid.ID, err error) {
	var ids []pulid.ID
	if ids, err = cbq.Limit(2).IDs(setContextOp(ctx, cbq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{carrierbring.Label}
	default:
		err = &NotSingularError{carrierbring.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cbq *CarrierBringQuery) OnlyIDX(ctx context.Context) pulid.ID {
	id, err := cbq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CarrierBrings.
func (cbq *CarrierBringQuery) All(ctx context.Context) ([]*CarrierBring, error) {
	ctx = setContextOp(ctx, cbq.ctx, ent.OpQueryAll)
	if err := cbq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CarrierBring, *CarrierBringQuery]()
	return withInterceptors[[]*CarrierBring](ctx, cbq, qr, cbq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cbq *CarrierBringQuery) AllX(ctx context.Context) []*CarrierBring {
	nodes, err := cbq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CarrierBring IDs.
func (cbq *CarrierBringQuery) IDs(ctx context.Context) (ids []pulid.ID, err error) {
	if cbq.ctx.Unique == nil && cbq.path != nil {
		cbq.Unique(true)
	}
	ctx = setContextOp(ctx, cbq.ctx, ent.OpQueryIDs)
	if err = cbq.Select(carrierbring.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cbq *CarrierBringQuery) IDsX(ctx context.Context) []pulid.ID {
	ids, err := cbq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cbq *CarrierBringQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cbq.ctx, ent.OpQueryCount)
	if err := cbq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cbq, querierCount[*CarrierBringQuery](), cbq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cbq *CarrierBringQuery) CountX(ctx context.Context) int {
	count, err := cbq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cbq *CarrierBringQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cbq.ctx, ent.OpQueryExist)
	switch _, err := cbq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cbq *CarrierBringQuery) ExistX(ctx context.Context) bool {
	exist, err := cbq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CarrierBringQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cbq *CarrierBringQuery) Clone() *CarrierBringQuery {
	if cbq == nil {
		return nil
	}
	return &CarrierBringQuery{
		config:      cbq.config,
		ctx:         cbq.ctx.Clone(),
		order:       append([]carrierbring.OrderOption{}, cbq.order...),
		inters:      append([]Interceptor{}, cbq.inters...),
		predicates:  append([]predicate.CarrierBring{}, cbq.predicates...),
		withTenant:  cbq.withTenant.Clone(),
		withCarrier: cbq.withCarrier.Clone(),
		// clone intermediate query.
		sql:  cbq.sql.Clone(),
		path: cbq.path,
	}
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (cbq *CarrierBringQuery) WithTenant(opts ...func(*TenantQuery)) *CarrierBringQuery {
	query := (&TenantClient{config: cbq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cbq.withTenant = query
	return cbq
}

// WithCarrier tells the query-builder to eager-load the nodes that are connected to
// the "carrier" edge. The optional arguments are used to configure the query builder of the edge.
func (cbq *CarrierBringQuery) WithCarrier(opts ...func(*CarrierQuery)) *CarrierBringQuery {
	query := (&CarrierClient{config: cbq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cbq.withCarrier = query
	return cbq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID pulid.ID `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CarrierBring.Query().
//		GroupBy(carrierbring.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cbq *CarrierBringQuery) GroupBy(field string, fields ...string) *CarrierBringGroupBy {
	cbq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CarrierBringGroupBy{build: cbq}
	grbuild.flds = &cbq.ctx.Fields
	grbuild.label = carrierbring.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID pulid.ID `json:"tenant_id,omitempty"`
//	}
//
//	client.CarrierBring.Query().
//		Select(carrierbring.FieldTenantID).
//		Scan(ctx, &v)
func (cbq *CarrierBringQuery) Select(fields ...string) *CarrierBringSelect {
	cbq.ctx.Fields = append(cbq.ctx.Fields, fields...)
	sbuild := &CarrierBringSelect{CarrierBringQuery: cbq}
	sbuild.label = carrierbring.Label
	sbuild.flds, sbuild.scan = &cbq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CarrierBringSelect configured with the given aggregations.
func (cbq *CarrierBringQuery) Aggregate(fns ...AggregateFunc) *CarrierBringSelect {
	return cbq.Select().Aggregate(fns...)
}

func (cbq *CarrierBringQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cbq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cbq); err != nil {
				return err
			}
		}
	}
	for _, f := range cbq.ctx.Fields {
		if !carrierbring.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cbq.path != nil {
		prev, err := cbq.path(ctx)
		if err != nil {
			return err
		}
		cbq.sql = prev
	}
	if carrierbring.Policy == nil {
		return errors.New("ent: uninitialized carrierbring.Policy (forgotten import ent/runtime?)")
	}
	if err := carrierbring.Policy.EvalQuery(ctx, cbq); err != nil {
		return err
	}
	return nil
}

func (cbq *CarrierBringQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CarrierBring, error) {
	var (
		nodes       = []*CarrierBring{}
		withFKs     = cbq.withFKs
		_spec       = cbq.querySpec()
		loadedTypes = [2]bool{
			cbq.withTenant != nil,
			cbq.withCarrier != nil,
		}
	)
	if cbq.withCarrier != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, carrierbring.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CarrierBring).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CarrierBring{config: cbq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(cbq.modifiers) > 0 {
		_spec.Modifiers = cbq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cbq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cbq.withTenant; query != nil {
		if err := cbq.loadTenant(ctx, query, nodes, nil,
			func(n *CarrierBring, e *Tenant) { n.Edges.Tenant = e }); err != nil {
			return nil, err
		}
	}
	if query := cbq.withCarrier; query != nil {
		if err := cbq.loadCarrier(ctx, query, nodes, nil,
			func(n *CarrierBring, e *Carrier) { n.Edges.Carrier = e }); err != nil {
			return nil, err
		}
	}
	for i := range cbq.loadTotal {
		if err := cbq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cbq *CarrierBringQuery) loadTenant(ctx context.Context, query *TenantQuery, nodes []*CarrierBring, init func(*CarrierBring), assign func(*CarrierBring, *Tenant)) error {
	ids := make([]pulid.ID, 0, len(nodes))
	nodeids := make(map[pulid.ID][]*CarrierBring)
	for i := range nodes {
		fk := nodes[i].TenantID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tenant.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tenant_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (cbq *CarrierBringQuery) loadCarrier(ctx context.Context, query *CarrierQuery, nodes []*CarrierBring, init func(*CarrierBring), assign func(*CarrierBring, *Carrier)) error {
	ids := make([]pulid.ID, 0, len(nodes))
	nodeids := make(map[pulid.ID][]*CarrierBring)
	for i := range nodes {
		if nodes[i].carrier_carrier_bring == nil {
			continue
		}
		fk := *nodes[i].carrier_carrier_bring
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(carrier.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "carrier_carrier_bring" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (cbq *CarrierBringQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cbq.querySpec()
	if len(cbq.modifiers) > 0 {
		_spec.Modifiers = cbq.modifiers
	}
	_spec.Node.Columns = cbq.ctx.Fields
	if len(cbq.ctx.Fields) > 0 {
		_spec.Unique = cbq.ctx.Unique != nil && *cbq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cbq.driver, _spec)
}

func (cbq *CarrierBringQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(carrierbring.Table, carrierbring.Columns, sqlgraph.NewFieldSpec(carrierbring.FieldID, field.TypeString))
	_spec.From = cbq.sql
	if unique := cbq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cbq.path != nil {
		_spec.Unique = true
	}
	if fields := cbq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, carrierbring.FieldID)
		for i := range fields {
			if fields[i] != carrierbring.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if cbq.withTenant != nil {
			_spec.Node.AddColumnOnce(carrierbring.FieldTenantID)
		}
	}
	if ps := cbq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cbq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cbq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cbq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cbq *CarrierBringQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cbq.driver.Dialect())
	t1 := builder.Table(carrierbring.Table)
	columns := cbq.ctx.Fields
	if len(columns) == 0 {
		columns = carrierbring.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cbq.sql != nil {
		selector = cbq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cbq.ctx.Unique != nil && *cbq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cbq.predicates {
		p(selector)
	}
	for _, p := range cbq.order {
		p(selector)
	}
	if offset := cbq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cbq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CarrierBringGroupBy is the group-by builder for CarrierBring entities.
type CarrierBringGroupBy struct {
	selector
	build *CarrierBringQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cbgb *CarrierBringGroupBy) Aggregate(fns ...AggregateFunc) *CarrierBringGroupBy {
	cbgb.fns = append(cbgb.fns, fns...)
	return cbgb
}

// Scan applies the selector query and scans the result into the given value.
func (cbgb *CarrierBringGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cbgb.build.ctx, ent.OpQueryGroupBy)
	if err := cbgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CarrierBringQuery, *CarrierBringGroupBy](ctx, cbgb.build, cbgb, cbgb.build.inters, v)
}

func (cbgb *CarrierBringGroupBy) sqlScan(ctx context.Context, root *CarrierBringQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cbgb.fns))
	for _, fn := range cbgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cbgb.flds)+len(cbgb.fns))
		for _, f := range *cbgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cbgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cbgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CarrierBringSelect is the builder for selecting fields of CarrierBring entities.
type CarrierBringSelect struct {
	*CarrierBringQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cbs *CarrierBringSelect) Aggregate(fns ...AggregateFunc) *CarrierBringSelect {
	cbs.fns = append(cbs.fns, fns...)
	return cbs
}

// Scan applies the selector query and scans the result into the given value.
func (cbs *CarrierBringSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cbs.ctx, ent.OpQuerySelect)
	if err := cbs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CarrierBringQuery, *CarrierBringSelect](ctx, cbs.CarrierBringQuery, cbs, cbs.inters, v)
}

func (cbs *CarrierBringSelect) sqlScan(ctx context.Context, root *CarrierBringQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cbs.fns))
	for _, fn := range cbs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cbs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cbs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
