// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"delivrio.io/go/ent/documentfile"
	"delivrio.io/go/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DocumentFileDelete is the builder for deleting a DocumentFile entity.
type DocumentFileDelete struct {
	config
	hooks    []Hook
	mutation *DocumentFileMutation
}

// Where appends a list predicates to the DocumentFileDelete builder.
func (dfd *DocumentFileDelete) Where(ps ...predicate.DocumentFile) *DocumentFileDelete {
	dfd.mutation.Where(ps...)
	return dfd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dfd *DocumentFileDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dfd.sqlExec, dfd.mutation, dfd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dfd *DocumentFileDelete) ExecX(ctx context.Context) int {
	n, err := dfd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dfd *DocumentFileDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(documentfile.Table, sqlgraph.NewFieldSpec(documentfile.FieldID, field.TypeString))
	if ps := dfd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dfd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dfd.mutation.done = true
	return affected, err
}

// DocumentFileDeleteOne is the builder for deleting a single DocumentFile entity.
type DocumentFileDeleteOne struct {
	dfd *DocumentFileDelete
}

// Where appends a list predicates to the DocumentFileDelete builder.
func (dfdo *DocumentFileDeleteOne) Where(ps ...predicate.DocumentFile) *DocumentFileDeleteOne {
	dfdo.dfd.mutation.Where(ps...)
	return dfdo
}

// Exec executes the deletion query.
func (dfdo *DocumentFileDeleteOne) Exec(ctx context.Context) error {
	n, err := dfdo.dfd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{documentfile.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dfdo *DocumentFileDeleteOne) ExecX(ctx context.Context) {
	if err := dfdo.Exec(ctx); err != nil {
		panic(err)
	}
}
