// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"delivrio.io/go/ent/orderline"
	"delivrio.io/go/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderLineDelete is the builder for deleting a OrderLine entity.
type OrderLineDelete struct {
	config
	hooks    []Hook
	mutation *OrderLineMutation
}

// Where appends a list predicates to the OrderLineDelete builder.
func (old *OrderLineDelete) Where(ps ...predicate.OrderLine) *OrderLineDelete {
	old.mutation.Where(ps...)
	return old
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (old *OrderLineDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, old.sqlExec, old.mutation, old.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (old *OrderLineDelete) ExecX(ctx context.Context) int {
	n, err := old.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (old *OrderLineDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(orderline.Table, sqlgraph.NewFieldSpec(orderline.FieldID, field.TypeString))
	if ps := old.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, old.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	old.mutation.done = true
	return affected, err
}

// OrderLineDeleteOne is the builder for deleting a single OrderLine entity.
type OrderLineDeleteOne struct {
	old *OrderLineDelete
}

// Where appends a list predicates to the OrderLineDelete builder.
func (oldo *OrderLineDeleteOne) Where(ps ...predicate.OrderLine) *OrderLineDeleteOne {
	oldo.old.mutation.Where(ps...)
	return oldo
}

// Exec executes the deletion query.
func (oldo *OrderLineDeleteOne) Exec(ctx context.Context) error {
	n, err := oldo.old.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{orderline.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (oldo *OrderLineDeleteOne) ExecX(ctx context.Context) {
	if err := oldo.Exec(ctx); err != nil {
		panic(err)
	}
}
