// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"delivrio.io/go/ent/predicate"
	"delivrio.io/go/ent/shipmentdsv"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShipmentDSVDelete is the builder for deleting a ShipmentDSV entity.
type ShipmentDSVDelete struct {
	config
	hooks    []Hook
	mutation *ShipmentDSVMutation
}

// Where appends a list predicates to the ShipmentDSVDelete builder.
func (sdd *ShipmentDSVDelete) Where(ps ...predicate.ShipmentDSV) *ShipmentDSVDelete {
	sdd.mutation.Where(ps...)
	return sdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sdd *ShipmentDSVDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sdd.sqlExec, sdd.mutation, sdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sdd *ShipmentDSVDelete) ExecX(ctx context.Context) int {
	n, err := sdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sdd *ShipmentDSVDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(shipmentdsv.Table, sqlgraph.NewFieldSpec(shipmentdsv.FieldID, field.TypeString))
	if ps := sdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sdd.mutation.done = true
	return affected, err
}

// ShipmentDSVDeleteOne is the builder for deleting a single ShipmentDSV entity.
type ShipmentDSVDeleteOne struct {
	sdd *ShipmentDSVDelete
}

// Where appends a list predicates to the ShipmentDSVDelete builder.
func (sddo *ShipmentDSVDeleteOne) Where(ps ...predicate.ShipmentDSV) *ShipmentDSVDeleteOne {
	sddo.sdd.mutation.Where(ps...)
	return sddo
}

// Exec executes the deletion query.
func (sddo *ShipmentDSVDeleteOne) Exec(ctx context.Context) error {
	n, err := sddo.sdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{shipmentdsv.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sddo *ShipmentDSVDeleteOne) ExecX(ctx context.Context) {
	if err := sddo.Exec(ctx); err != nil {
		panic(err)
	}
}
