-- Disable the enforcement of foreign-keys constraints
PRAGMA foreign_keys = off;
-- Create "new_delivery_options" table
CREATE TABLE `new_delivery_options` (`id` text NOT NULL, `archived_at` datetime NULL, `name` text NOT NULL, `sort_order` integer NOT NULL, `click_option_display_count` integer NULL DEFAULT (3), `description` text NULL, `click_collect` bool NULL DEFAULT (false), `override_sender_address` bool NULL DEFAULT (false), `override_return_address` bool NULL DEFAULT (false), `hide_delivery_option` bool NULL DEFAULT (false), `delivery_estimate_from` integer NULL, `delivery_estimate_to` integer NULL, `webshipper_integration` bool NOT NULL DEFAULT (false), `webshipper_id` integer NULL DEFAULT (1), `shipmondo_integration` bool NOT NULL DEFAULT (false), `shipmondo_delivery_option` text NULL, `customs_enabled` bool NOT NULL DEFAULT (false), `customs_signer` text NULL, `hide_if_company_empty` bool NOT NULL DEFAULT (false), `connection_delivery_option` text NOT NULL, `connection_default_delivery_option` text NULL, `tenant_id` text NOT NULL, `delivery_option_carrier` text NOT NULL, `delivery_option_carrier_service` text NOT NULL, `delivery_option_email_click_collect_at_store` text NULL, `delivery_option_default_packaging` text NULL, PRIMARY KEY (`id`), CONSTRAINT `delivery_options_connections_delivery_option` FOREIGN KEY (`connection_delivery_option`) REFERENCES `connections` (`id`) ON DELETE NO ACTION, CONSTRAINT `delivery_options_connections_default_delivery_option` FOREIGN KEY (`connection_default_delivery_option`) REFERENCES `connections` (`id`) ON DELETE SET NULL, CONSTRAINT `delivery_options_tenants_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE NO ACTION, CONSTRAINT `delivery_options_carriers_carrier` FOREIGN KEY (`delivery_option_carrier`) REFERENCES `carriers` (`id`) ON DELETE NO ACTION, CONSTRAINT `delivery_options_carrier_services_carrier_service` FOREIGN KEY (`delivery_option_carrier_service`) REFERENCES `carrier_services` (`id`) ON DELETE NO ACTION, CONSTRAINT `delivery_options_email_templates_email_click_collect_at_store` FOREIGN KEY (`delivery_option_email_click_collect_at_store`) REFERENCES `email_templates` (`id`) ON DELETE SET NULL, CONSTRAINT `delivery_options_packagings_default_packaging` FOREIGN KEY (`delivery_option_default_packaging`) REFERENCES `packagings` (`id`) ON DELETE SET NULL);
-- Copy rows from old table "delivery_options" to new temporary table "new_delivery_options"
INSERT INTO `new_delivery_options` (`id`, `archived_at`, `name`, `sort_order`, `click_option_display_count`, `description`, `click_collect`, `override_sender_address`, `override_return_address`, `hide_delivery_option`, `delivery_estimate_from`, `delivery_estimate_to`, `webshipper_integration`, `webshipper_id`, `shipmondo_integration`, `shipmondo_delivery_option`, `customs_enabled`, `customs_signer`, `connection_delivery_option`, `connection_default_delivery_option`, `tenant_id`, `delivery_option_carrier`, `delivery_option_carrier_service`, `delivery_option_email_click_collect_at_store`, `delivery_option_default_packaging`) SELECT `id`, `archived_at`, `name`, `sort_order`, `click_option_display_count`, `description`, `click_collect`, `override_sender_address`, `override_return_address`, `hide_delivery_option`, `delivery_estimate_from`, `delivery_estimate_to`, `webshipper_integration`, `webshipper_id`, `shipmondo_integration`, `shipmondo_delivery_option`, `customs_enabled`, `customs_signer`, `connection_delivery_option`, `connection_default_delivery_option`, `tenant_id`, `delivery_option_carrier`, `delivery_option_carrier_service`, `delivery_option_email_click_collect_at_store`, `delivery_option_default_packaging` FROM `delivery_options`;
-- Drop "delivery_options" table after copying rows
DROP TABLE `delivery_options`;
-- Rename temporary table "new_delivery_options" to "delivery_options"
ALTER TABLE `new_delivery_options` RENAME TO `delivery_options`;
-- Create index "delivery_options_connection_default_delivery_option_key" to table: "delivery_options"
CREATE UNIQUE INDEX `delivery_options_connection_default_delivery_option_key` ON `delivery_options` (`connection_default_delivery_option`);
-- Create index "deliveryoption_tenant_id" to table: "delivery_options"
CREATE INDEX `deliveryoption_tenant_id` ON `delivery_options` (`tenant_id`);
-- Enable back the enforcement of foreign-keys constraints
PRAGMA foreign_keys = on;
