query FetchPlatformsCarriers {
	connectOptionCarriers {
		edges {
			node {
				name
				id
			}
		}
	}
	connectOptionPlatforms {
		edges {
			node {
				name
				id
			}
		}
	}
}

mutation ReplaceCarriersPlatforms($userID: ID!, $inputCarriers: [ID!]!, $inputPlatforms: [ID!]!) {
	replaceInterestedCarriersPlatforms(userID: $userID, inputCarriers: $inputCarriers, inputPlatforms: $inputPlatforms) {
		id
	}
}
