
build-returns:
	npm run-script build:returns
	cat dist/return-portal/browser/polyfills.js > dist/return-portal/browser/return-bundle.js
	cat dist/return-portal/browser/main.js >> dist/return-portal/browser/return-bundle.js

