// Code generated by ent, DO NOT EDIT.

package deliveryoptioneasypost

import (
	"delivrio.io/go/ent/predicate"
	"delivrio.io/shared-utils/pulid"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id pulid.ID) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id pulid.ID) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id pulid.ID) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...pulid.ID) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...pulid.ID) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id pulid.ID) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id pulid.ID) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id pulid.ID) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id pulid.ID) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v pulid.ID) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v pulid.ID) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v pulid.ID) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...pulid.ID) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...pulid.ID) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v pulid.ID) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v pulid.ID) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v pulid.ID) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v pulid.ID) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v pulid.ID) predicate.DeliveryOptionEasyPost {
	vc := string(v)
	return predicate.DeliveryOptionEasyPost(sql.FieldContains(FieldTenantID, vc))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v pulid.ID) predicate.DeliveryOptionEasyPost {
	vc := string(v)
	return predicate.DeliveryOptionEasyPost(sql.FieldHasPrefix(FieldTenantID, vc))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v pulid.ID) predicate.DeliveryOptionEasyPost {
	vc := string(v)
	return predicate.DeliveryOptionEasyPost(sql.FieldHasSuffix(FieldTenantID, vc))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v pulid.ID) predicate.DeliveryOptionEasyPost {
	vc := string(v)
	return predicate.DeliveryOptionEasyPost(sql.FieldEqualFold(FieldTenantID, vc))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v pulid.ID) predicate.DeliveryOptionEasyPost {
	vc := string(v)
	return predicate.DeliveryOptionEasyPost(sql.FieldContainsFold(FieldTenantID, vc))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDeliveryOption applies the HasEdge predicate on the "delivery_option" edge.
func HasDeliveryOption() predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, DeliveryOptionTable, DeliveryOptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeliveryOptionWith applies the HasEdge predicate on the "delivery_option" edge with a given conditions (other predicates).
func HasDeliveryOptionWith(preds ...predicate.DeliveryOption) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(func(s *sql.Selector) {
		step := newDeliveryOptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCarrierAddServEasyPost applies the HasEdge predicate on the "carrier_add_serv_easy_post" edge.
func HasCarrierAddServEasyPost() predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, CarrierAddServEasyPostTable, CarrierAddServEasyPostPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCarrierAddServEasyPostWith applies the HasEdge predicate on the "carrier_add_serv_easy_post" edge with a given conditions (other predicates).
func HasCarrierAddServEasyPostWith(preds ...predicate.CarrierAdditionalServiceEasyPost) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(func(s *sql.Selector) {
		step := newCarrierAddServEasyPostStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DeliveryOptionEasyPost) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DeliveryOptionEasyPost) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DeliveryOptionEasyPost) predicate.DeliveryOptionEasyPost {
	return predicate.DeliveryOptionEasyPost(sql.NotPredicates(p))
}
