version: '3.8'

services:
  db:
    image: postgres:16
    container_name: delivrio-postgres
    environment:
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: