// Code generated by ent, DO NOT EDIT.

package changehistory

import (
	"time"

	"delivrio.io/go/ent/predicate"
	"delivrio.io/shared-utils/pulid"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id pulid.ID) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id pulid.ID) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id pulid.ID) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...pulid.ID) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...pulid.ID) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id pulid.ID) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id pulid.ID) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id pulid.ID) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id pulid.ID) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v pulid.ID) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldEQ(FieldTenantID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v pulid.ID) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v pulid.ID) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...pulid.ID) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...pulid.ID) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v pulid.ID) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v pulid.ID) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v pulid.ID) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v pulid.ID) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v pulid.ID) predicate.ChangeHistory {
	vc := string(v)
	return predicate.ChangeHistory(sql.FieldContains(FieldTenantID, vc))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v pulid.ID) predicate.ChangeHistory {
	vc := string(v)
	return predicate.ChangeHistory(sql.FieldHasPrefix(FieldTenantID, vc))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v pulid.ID) predicate.ChangeHistory {
	vc := string(v)
	return predicate.ChangeHistory(sql.FieldHasSuffix(FieldTenantID, vc))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v pulid.ID) predicate.ChangeHistory {
	vc := string(v)
	return predicate.ChangeHistory(sql.FieldEqualFold(FieldTenantID, vc))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v pulid.ID) predicate.ChangeHistory {
	vc := string(v)
	return predicate.ChangeHistory(sql.FieldContainsFold(FieldTenantID, vc))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldLTE(FieldCreatedAt, v))
}

// OriginEQ applies the EQ predicate on the "origin" field.
func OriginEQ(v Origin) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldEQ(FieldOrigin, v))
}

// OriginNEQ applies the NEQ predicate on the "origin" field.
func OriginNEQ(v Origin) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldNEQ(FieldOrigin, v))
}

// OriginIn applies the In predicate on the "origin" field.
func OriginIn(vs ...Origin) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldIn(FieldOrigin, vs...))
}

// OriginNotIn applies the NotIn predicate on the "origin" field.
func OriginNotIn(vs ...Origin) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.FieldNotIn(FieldOrigin, vs...))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.ChangeHistory {
	return predicate.ChangeHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.ChangeHistory {
	return predicate.ChangeHistory(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlanHistory applies the HasEdge predicate on the "plan_history" edge.
func HasPlanHistory() predicate.ChangeHistory {
	return predicate.ChangeHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PlanHistoryTable, PlanHistoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlanHistoryWith applies the HasEdge predicate on the "plan_history" edge with a given conditions (other predicates).
func HasPlanHistoryWith(preds ...predicate.PlanHistory) predicate.ChangeHistory {
	return predicate.ChangeHistory(func(s *sql.Selector) {
		step := newPlanHistoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ChangeHistory {
	return predicate.ChangeHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ChangeHistory {
	return predicate.ChangeHistory(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOrderHistory applies the HasEdge predicate on the "order_history" edge.
func HasOrderHistory() predicate.ChangeHistory {
	return predicate.ChangeHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OrderHistoryTable, OrderHistoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrderHistoryWith applies the HasEdge predicate on the "order_history" edge with a given conditions (other predicates).
func HasOrderHistoryWith(preds ...predicate.OrderHistory) predicate.ChangeHistory {
	return predicate.ChangeHistory(func(s *sql.Selector) {
		step := newOrderHistoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasShipmentHistory applies the HasEdge predicate on the "shipment_history" edge.
func HasShipmentHistory() predicate.ChangeHistory {
	return predicate.ChangeHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ShipmentHistoryTable, ShipmentHistoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShipmentHistoryWith applies the HasEdge predicate on the "shipment_history" edge with a given conditions (other predicates).
func HasShipmentHistoryWith(preds ...predicate.ShipmentHistory) predicate.ChangeHistory {
	return predicate.ChangeHistory(func(s *sql.Selector) {
		step := newShipmentHistoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReturnColliHistory applies the HasEdge predicate on the "return_colli_history" edge.
func HasReturnColliHistory() predicate.ChangeHistory {
	return predicate.ChangeHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ReturnColliHistoryTable, ReturnColliHistoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReturnColliHistoryWith applies the HasEdge predicate on the "return_colli_history" edge with a given conditions (other predicates).
func HasReturnColliHistoryWith(preds ...predicate.ReturnColliHistory) predicate.ChangeHistory {
	return predicate.ChangeHistory(func(s *sql.Selector) {
		step := newReturnColliHistoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChangeHistory) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChangeHistory) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChangeHistory) predicate.ChangeHistory {
	return predicate.ChangeHistory(sql.NotPredicates(p))
}
